### ISSUE TITLE
Unexpected token, expected ";"

### ISSUE THREAD

**Issue by rahulyagi** [aalises/preact-typescript-parcel-starter#1]
Getting this syntaxError in index.tsx
Just cloned the repo, did yarn and yarn build

**Comment by r0skar** [comment]
This is related to `parcel-plugin-typescript`. Removing the plugin solves the issue. You wont get live errors from TS, but I actually prefer it this way. Note: you will also want to change the top-level import in `src/store/store.ts` to `import createStore from "redux-zero";`
